services:
  - type: web
    name: reconx-automated-recon-tool
    env: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.10
  - type: pgsql
    name: reconx-database
    databaseName: reconx
    user: reconx